services:
  sf-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./../:/app:cached
    command: sleep infinity
    networks:
      - dev_network

networks:
  dev_network:
    name: dev_network
    driver: bridge
